CONFIG_GPIO=y

# fix bootloader offset
CONFIG_FLASH_LOAD_OFFSET=0x1000
CONFIG_BOARD_HAS_NRF5_BOOTLOADER=y
CONFIG_USE_DT_CODE_PARTITION=n

# build uf2 bin
CONFIG_BUILD_OUTPUT_UF2=y

# USB USBD (new API) - HID + CDC ACM console
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n
CONFIG_USBD_HID_SUPPORT=y
CONFIG_SAMPLE_USBD_PID=0x0007

# Logging
CONFIG_LOG=y
CONFIG_USBD_LOG_LEVEL_WRN=y
CONFIG_USBD_HID_LOG_LEVEL_WRN=y
CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=y

# Console on CDC ACM
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y

# AS5600 sensor
CONFIG_SENSOR=y
CONFIG_AMS_AS5600=y
CONFIG_I2C=y

